
#' Builder for the association plot using ggplot2.
#'
#' @param asso_res     A \code{data.table} generated by
#'                     \link{test_asso_annot_pc} containing association tests'
#'                     results between a table of annotation and a set of
#'                     principal components.
#' @param dataset.name A \code{character} string specifying the name you want to
#'                     give to your dataset, that will be included in the plot
#'                     title (Default: dataset.name = "dataset").
#' @param PC.origin    A \code{character} string specifying what kind of data
#'                     the prcomp object has been computed from, especially if
#'                     it has been computed on a subset of the initial dataset
#'                     (e.g. 'PCs from ...') it will be appended to the plot
#'                     title (Default: PC.origin = NULL).
#' @param p.treshold   A \code{numeric} specifying a value for the P-value
#'                     significance threshold (Default: p.treshold = 0.05).
#' @return A \code{gg} plot summarizing results from associations tests between
#'         dataset's annotations and principal components.
#' @author Yoann Pageaud.
#' @keywords internal

build_asso_plot <- function(
    asso_res, dataset.name = "dataset", PC.origin = NULL, p.treshold = 0.05){
    # Plot association tests results
    max_log_pval <- ceiling(max(asso_res$log_trans_pval, na.rm = TRUE))
    asso_plot <- ggplot() +
        geom_point(data = asso_res, mapping = aes(
            x = PC, y = annotation, size = var.explained,
            fill = log_trans_pval, color = Significance), shape = 21) +
        facet_grid(rows = vars(test), scales = "free", space = "free") +
        scale_size_continuous(
            range = c(3, 20), limits = c(0, 500),
            breaks = c(0, 20, 40, 60, 80, 100),
            labels = paste0(seq(0,100, 20), "%")) +
        scale_fill_gradient2(
            low = "darkblue", mid = "white", high = "darkred",
            midpoint = -log10(p.treshold), limits = c(
                0, max_log_pval), breaks = seq(0, max_log_pval, by = 1)) +
        scale_color_manual(values = c("red", "grey")) +
        theme(axis.text = element_text(size = 12, colour = "black"),
              axis.title = element_text(size = 14),
              panel.background = element_rect(fill = "white", colour = "black"),
              panel.grid = element_line(colour = "black", linewidth = 0.1),
              legend.text = element_text(size = 11), legend.box.just = "left",
              legend.key = element_blank(), legend.title.align = 0.5,
              strip.background = element_rect(fill = "white", colour = "black"),
              strip.text = element_text(size = 11),
              plot.title = element_text(hjust = 0.5)) +
        guides(fill = guide_colorbar(
            ticks.colour = "black", frame.colour = "black")) +
        labs(x = "Top principal components", y = "Annotations",
             fill = "-Log10(P.value)", size = "PC variability\nexplained") +
        ggtitle(paste(
            "Associations between annotations and principal components from",
            dataset.name, PC.origin))
    return(asso_plot)
}

#' Plots association tests' results between some annotations and some PCs.
#'
#' @param annot.table  A \code{data.frame} containing annotations, 1 annotation
#'                     per column.
#' @param prcomp.res A PCA result of classes \code{prcomp} or
#'                   \code{irlba_prcomp} resulting from stats::prcomp() or
#'                   irlba::prcomp_irlba().
#' @param perm.count An \code{integer} specifying the number of permutations to
#'                   realize on a vector, for the permutations matrix
#'                   initialization, to be used for calculating the significance
#'                   of a correlation test (Default: perm.count = 10000).
#' @param max.PCs    An \code{integer} specifying the maximum number of
#'                   principal components to consider for association tests with
#'                   annotations (Default: max.PCs = 8).
#' @param p.treshold A \code{numeric} specifying a value for the P-value
#'                   significance threshold (Default: p.treshold = 0.05).
#' @param dataset.name A \code{character} string specifying the name you want to
#'                     give to your dataset, that will be included in the plot
#'                     title (Default: dataset.name = "dataset").
#' @param PC.origin  A \code{character} string specifying what kind of data the
#'                    prcomp object has been computed from (e.g. 'mtcars',
#'                    'iris', 'mpg', ...) to be appended to the plot title.
#' @param verbose    A \code{logical} to display information about the
#'                   step-by-step processing of the data if TRUE
#'                   (Default: verbose = FALSE).
#' @return A \code{type} object returned description.
#' @author Yoann Pageaud.
#' @export
#' @examples
#' # Create mtcars annotation table
#' mtcars_annot <- data.table::as.data.table(
#'     mtcars[, c("cyl", "vs", "am", "gear", "carb")], keep.rownames = "cars")
#' # Create mtcars matrix with scaled and transposed data
#' mat_mtcars <- scale(as.matrix(
#'     mtcars[, c("mpg", "disp", "hp", "drat", "wt", "qsec")]))
#' # Compute PCA on mtcars matrix
#' pcs_mtcars <- prcomp(x = mat_mtcars)
#' # Plot association tests' results between annotations and PCs
#' plot_asso_annot_PC(
#'     annot.table = mtcars_annot, prcomp.res = pcs_mtcars,
#'     dataset.name = "mtcars", PC.origin = "mpg, disp, hp, drat, wt & qsec",
#'     verbose = TRUE)

plot_asso_annot_PC <- function(
    annot.table, prcomp.res, perm.count = 10000, max.PCs = 8, p.treshold = 0.05,
    dataset.name = "dataset", PC.origin = NULL, verbose = FALSE){
    # Compute association tests between annotations and PCs
    asso_res <- test_asso_annot_pc(
        annot.table = annot.table, prcomp.res = prcomp.res,
        perm.count = perm.count, max.PCs = max.PCs, verbose = verbose)
    # Add P-value treshold to the results
    asso_res[pvalue <= p.treshold, Significance := paste("P <=", p.treshold)]
    asso_res[pvalue > p.treshold, Significance := paste("P >", p.treshold)]
    # Plot association tests results
    asso_plot <- build_asso_plot(
        asso_res = asso_res, dataset.name = dataset.name, PC.origin = PC.origin,
        p.treshold = p.treshold)
    return(asso_plot)
}

#' Draws association test results between all columns from a data.frame.
#'
#' @param annot.table  A \code{data.frame} containing annotations, 1 annotation
#'                     per column.
#' @param perm.count   An \code{integer} specifying the number of permutations
#'                     to realize on a vector, for the permutations matrix
#'                     initialization, to be used for calculating the
#'                     significance of a correlation test
#'                     (Default: perm.count = 10000).
#' @param cohort.name  A \code{character} string specifying the name you want to
#'                     give to your dataset, that will be included in the plot
#'                     title (Default: cohort.name = "dataset").
#' @param verbose      A \code{logical} to display information about the
#'                     step-by-step processing of the data if TRUE
#'                     (Default: verbose = FALSE).
#' @return A \code{gg} plot.
#' @author Yoann Pageaud.
#' @export
#' @examples
#' # Create mtcars annotation table
#' mtcars_annot <- data.table::as.data.table(
#'     mtcars[, c("cyl", "vs", "am", "gear", "carb")], keep.rownames = "cars")
#' # Plot association tests' results between all annotations
#' plot_asso_all_annot(
#'     annot.table = mtcars_annot, cohort.name = "mtcars_annot", verbose = TRUE)

plot_asso_all_annot <- function(
    annot.table, perm.count = 10000, cohort.name = "dataset", verbose = FALSE){
    # Compute association tests between all annotations
    asso_res <- test_asso_all_annot(
        annot.table = annot.table, perm.count = perm.count, verbose = verbose)
    # Plot association tests results
    max_log_pval <- ceiling(max(asso_res$log_trans_pval, na.rm = TRUE))
    asso_plot <- ggplot2::ggplot(
        data = asso_res, mapping = ggplot2::aes(
            x = annotation1, y = annotation2, fill = log_trans_pval,
            color = test, label = round(log_trans_pval, 1))) +
        ggplot2::geom_tile(size = 1, width = 0.8, height = 0.8) +
        ggplot2::geom_text(color = "black") +
        ggplot2::scale_fill_gradient2(
            low = "darkblue", mid = "white", high = "darkred",
            midpoint = -log10(0.05), limits = c(
                0, max_log_pval), breaks = seq(0, max_log_pval, by = 1)) +
        ggplot2::theme(
            axis.text = ggplot2::element_text(size = 12, colour = "black"),
            axis.text.x = ggplot2::element_text(
                angle = -45, hjust = 0, vjust = 0.1),
            axis.title = ggplot2::element_blank(),
            axis.ticks = ggplot2::element_blank(),
            panel.background = ggplot2::element_rect(fill = NA, colour = NA),
            panel.grid = ggplot2::element_line(
                colour = "black", linewidth = 0.5),
            legend.text = ggplot2::element_text(size = 11),
            legend.box.just = "left",
            plot.title = ggplot2::element_text(hjust = 0.5)) +
        ggplot2::guides(fill = ggplot2::guide_colorbar(
            ticks.colour = "black", frame.colour = "black")) +
        ggplot2::labs(fill = "-Log10(P.value)", color = "Stat. test used") +
        ggplot2::ggtitle(
            paste("Associations between all annotations from", cohort.name))
    return(asso_plot)
}
