
#' Builder for the association plot using ggplot2.
#'
#' @param asso_res     A \code{data.table} generated by
#'                     \link{test_asso_annot_pc} containing association tests'
#'                     results between a table of annotation and a set of
#'                     principal components.
#' @param dataset.name A \code{character} string specifying the name you want to
#'                     give to your dataset, that will be included in the plot
#'                     title (Default: dataset.name = "dataset").
#' @param PC.origin    A \code{character} string specifying what kind of data
#'                     the prcomp object has been computed from, especially if
#'                     it has been computed on a subset of the initial dataset
#'                     (e.g. 'PCs from ...') it will be appended to the plot
#'                     title (Default: PC.origin = NULL).
#' @return A \code{gg} plot summarizing results from associations tests between
#'         dataset's annotations and principal components.
#' @author Yoann Pageaud.
#' @keywords internal

build_asso_plot <- function(
    asso_res, dataset.name = "dataset", PC.origin = NULL){
    # Plot association tests results
    max_log_pval <- ceiling(max(asso_res$log_trans_pval, na.rm = TRUE))
    asso_plot <- ggplot() +
        geom_point(data = asso_res, mapping = aes(
            x = PC, y = annotation, size = var.explained,
            fill = log_trans_pval), shape = 21) +
        facet_grid(rows = vars(test), scales = "free", space = "free") +
        scale_size_continuous(
            range = c(3, 20), limits = c(0, 500),
            breaks = c(0, 20, 40, 60, 80, 100),
            labels = paste0(seq(0,100, 20), "%")) +
        scale_fill_gradient2(
            low = "darkblue", mid = "white", high = "darkred",
            midpoint = -log10(0.05), limits = c(
                0, max_log_pval), breaks = seq(0, max_log_pval, by = 1)) +
        theme(axis.text = element_text(size = 12, colour = "black"),
              axis.title = element_text(size = 14),
              panel.background = element_rect(fill = "white", colour = "black"),
              panel.grid = element_line(colour = "black", size = 0.1),
              legend.text = element_text(size = 11), legend.box.just = "left",
              legend.key = element_blank(), legend.title.align = 0.5,
              strip.background = element_rect(fill = "white", colour = "black"),
              strip.text = element_text(size = 11),
              plot.title = element_text(hjust = 0.5)) +
        guides(fill = guide_colorbar(
            ticks.colour = "black", frame.colour = "black")) +
        labs(x = "Top principal components", y = "Annotations",
             fill = "-Log10(P.value)", size = "PC variability\nexplained") +
        ggtitle(paste(
            "Associations between annotations and principal components from",
            dataset.name, PC.origin))
    return(asso_plot)
}

#' Plots association tests' results between some annotations and some PCs.
#'
#' @param param1 A \code{type} parameter description.
#' @return A \code{type} object returned description.
#' @author Yoann Pageaud.
#' @export
#' @examples
#' # Create mtcars annotation table
#' mtcars_annot <- data.table::as.data.table(
#'     mtcars[, c("cyl", "vs", "am", "gear", "carb")], keep.rownames = "cars")
#' # Create mtcars matrix with scaled and transposed data
#' mat_mtcars <- scale(as.matrix(
#'     mtcars[, c("mpg", "disp", "hp", "drat", "wt", "qsec")]))
#' # Compute PCA on mtcars matrix
#' pcs_mtcars <- prcomp(x = mat_mtcars)
#' # Plot association tests' results between annotations and PCs
#' plot_asso_annot_PC(
#'     annot.table = mtcars_annot, prcomp.res = pcs_mtcars,
#'     dataset.name = "mtcars", PC.origin = "mpg, disp, hp, drat, wt & qsec",
#'     verbose = TRUE)

plot_asso_annot_PC <- function(
    annot.table, prcomp.res, perm.count = 10000, max.PCs = 8,
    dataset.name = "dataset", PC.origin = NULL, verbose = FALSE){
    # Compute association tests between annotations and PCs
    asso_res <- test_asso_annot_pc(
        annot.table = annot.table, prcomp.res = prcomp.res,
        perm.count = perm.count, max.PCs = max.PCs, verbose = verbose)
    # Plot association tests results
    asso_plot <- build_asso_plot(
        asso_res = asso_res, dataset.name = dataset.name, PC.origin = PC.origin)
    return(asso_plot)
}
